website_url: 'https://www.erdo.dev'
website_name: 'erdo.dev'
author: 'Erdem'

directories:
  pages: 'pages'
  blog: 'blog'
  public: 'public'
  output: 'build'
  blog_output: 'build/blog'

files:
  root_index: 'index.md'
  blog_index: 'pages/blog.md'
  contact_index: 'pages/contact.md'
  rss_feed: 'build/rss.xml'

templates:
  header: 'header.html'
  footer: 'footer.html'

misc:
  recent_posts_count: 5
  generate_rss: True