name: build-deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML Markdown PyRSS2Gen
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Generate static files
        run: |
          python bloggen.py
          echo "Build complete!"
          
      - name: Configure git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Deploy to deploy branch
        run: |
          git fetch
          git checkout deploy 2>/dev/null || git checkout --orphan deploy
          git rm -rf . 2>/dev/null || true
          cp -r build/* .
          rm -rf build/
          git add .
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin deploy --force

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
